---
- name: Install Ansible
  hosts: TOMCAT-server1
  become: true
  tasks:
    - name: Install EPEL repository
      yum:
        name: epel-release
        state: present

    - name: Install Ansible
      yum:
        name: ansible
        state: present
